version: 0.0
os: windows 
files:
  - source: CoreWithNUnit/CoreWithNUnit/build_output/
    destination: C:\inetpub\wwwroot\CoreWithNUnit
  
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      #runas: root
 
  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      #runas: root
