version: 0.0
os: linux 
files:
   - source: /CoreWithNUnit/build_output/
    destination: C:\inetpub\wwwroot\CoreWithNUnit
    
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_python3
      timeout: 300
      runas: root

    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root

  