version: 0.0
os: windows 
files:
  - source: /CoreWithNUnit/build_output/
    destination: C:\inetpub\wwwroot\CoreWithNUnit
  
hooks:
  BeforeInstall:
    - location: C:\bat\before-install.bat
      timeout: 900
      